# Generated by Django 5.0.6 on 2024-11-12 20:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('a8abd77e-b45c-489e-8ac0-f2ba5384cb8f')),
        ),
    ]
