# Generated by Django 5.0.6 on 2024-11-12 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('e06ac5a8-8413-4917-a55e-b5a0006fb975')),
        ),
    ]
