# Generated by Django 5.0.6 on 2024-11-13 00:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('5e42f327-6b76-46db-a520-d8c9f968bdbc')),
        ),
    ]
