# Generated by Django 3.2.6 on 2021-08-18 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('63f857fd-e4af-4d68-9f3e-4e7fafdb2dd1')),
        ),
    ]
