# Generated by Django 3.1.4 on 2021-07-20 18:43

import accounts.utils
from django.db import migrations, models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.utils.upload_avatar_directory),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('2cfb583d-5dae-4bac-8e28-a3916c070aab')),
        ),
    ]
