# Generated by Django 4.0.1 on 2022-07-22 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subscriber_alter_myuserprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.UUIDField(default=uuid.UUID('b1af9da3-bc4e-4cb7-8b55-a8740ca1aefd')),
        ),
    ]
