# Generated by Django 5.0.6 on 2024-11-12 23:29

import django_seo.utils
import django_seo.validators
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('legal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_place', models.CharField(blank=True, help_text='Place where the company was registered', max_length=200, null=True)),
                ('company_type', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', help_text="'A' for commerce, 'B' for company", max_length=2)),
                ('siren', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django_seo.validators.validate_siren], verbose_name='SIREN')),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django_seo.validators.validate_siret], verbose_name='SIRET')),
                ('ape', models.CharField(blank=True, help_text='The APE code for the business', max_length=5, null=True, validators=[django_seo.validators.validate_ape], verbose_name='Code APE')),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('general_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_service_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line', models.CharField(blank=True, max_length=300, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Ideally should be a square e.g. 200x200', null=True, upload_to=django_seo.utils.upload_logo_to)),
            ],
            options={
                'verbose_name_plural': 'legal businesses',
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='PageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('social_title', models.CharField(blank=True, max_length=100, null=True)),
                ('social_image', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('social_description', models.TextField(blank=True, max_length=155, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Meta keywords', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description which should ideally be between a 100 and 155 characters which is specific to a given page', max_length=155, null=True)),
                ('same_descriptions', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchEngineDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('author', models.CharField(blank=True, help_text="Author or founder of the company'", max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Meta keywords', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description which should ideally be between a 100 and 155 characters. This is a global description for a all the pages', max_length=155, null=True)),
                ('theme_color', models.CharField(blank=True, default='2d2d2d', max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn business page', null=True)),
                ('facebook', models.URLField(blank=True, help_text='Facebook business page', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile page', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter business page', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel', null=True)),
                ('tiktok', models.URLField(blank=True, help_text='Tiktok page', null=True)),
            ],
            options={
                'ordering': ['version'],
                'abstract': False,
            },
        ),
    ]
