# Generated by Django 5.0.6 on 2024-11-13 00:08

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchenginedetail',
            name='pages',
            field=models.ManyToManyField(blank=True, to='django_seo.pagedetail'),
        ),
        migrations.AlterField(
            model_name='legalbusiness',
            name='company_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', help_text="'A' for commerce, 'B' for company", max_length=2),
        ),
        migrations.AlterField(
            model_name='pagedetail',
            name='social_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
